Conversation
slavb18/autoclick pull request #16
Opened 2021-04-03 17:55 UTC by WarTovsk

2021-04-03 19:17 UTC, slavb18 requested changes
React-bootstrap не нужно использовать, 
Нужно использовать semantic ui react

2021-04-04 17:19 UTC, WarTovsk commented
будет ли useContext или провайдер Redux? 
--
Отправлено из Mail.ru для Android суббота, 03 апреля 2021г., 22:17 +03:00 от slavb18  ***@***.*** :

***@***.*** requested changes on this pull request.
>React-bootstrap не нужно использовать,
>Нужно использовать semantic ui react
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-04-05 04:33 UTC, slavb18 commented
Нет, будет использоваться getServerSideProps

> будет ли useContext или провайдер Redux? -- Отправлено из Mail.ru для Android суббота, 03 апреля 2021г., 22:17 +03:00 от slavb18 ***@***.*** : ***@***.*** requested changes on this pull request.

2021-04-05 12:44 UTC, WarTovsk commented
переделал 
--
Отправлено из Mail.ru для Android понедельник, 05 апреля 2021г., 07:33 +03:00 от slavb18  ***@***.*** :

>Нет, будет использоваться getServerSideProps
>>будет ли useContext или провайдер Redux? -- Отправлено из Mail.ru для Android суббота, 03 апреля 2021г., 22:17 +03:00 от slavb18  @ .*** :  @ .*** requested changes on this pull request.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2021-04-05 13:25 UTC, merged